name: Function Composition Push

on: 
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'function-images/tests/**'
      - '.github/workflows/image_build.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'function-images/tests/**'
      - '.github/workflows/image_build.yml'
  schedule:
    - cron: '0 9 * * 1'
  
env:
  GOOS: linux
  GO111MODULE: on
  VHIVE_GOLANG_VERSION: golang:1.16.4-alpine3.13

jobs:
  push-golang:
    name: Push Golang build image
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
    steps:

    - uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
          context: ./configs/golang/
          file: ./configs/golang/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/golang:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.VHIVE_GOLANG_VERSION }}

  push-chained-functions-serving:
    name: Push chained-functions-serving-*
    needs: push-golang
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
    steps:

    - uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      working-directory: ./function-images/tests/chained-function-serving
      run: |
        make all-image
        make all-image-push

  push-chained-functions-eventing:
      name: Push chained-functions-eventing-*
      needs: push-golang
      runs-on: ubuntu-18.04
      strategy:
        fail-fast: false
      steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        working-directory: ./function-images/tests/chained-function-eventing
        run: make push-all

  push-video-processing:
    name: Push Video Analytics images
    needs: push-golang
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
    steps:

    - uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      working-directory: ./function-images/tests/video-bench
      run: |
        make all-image
        make all-image-push

